# Generated by Django 6.0.1 on 2026-01-17 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requesting_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requesting_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_swaps', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='target_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_swaps', to='shifts.shift'),
        ),
    ]
